name: Test exercise 1
on : push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name : checkout
            uses : actions/checkout@v4
          - run : echo "💡 The ${{ github.repository }} repository has been cloned to the runner." 
          - name: download dependencies
            run : npm i
          - name: check code
            run : |
                npm run lint
                npm run test
                npm run build
            
            
